import "@/styles/globals.css";
iimport { useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';

const CLIENT_ID = "22ed42382ae44ed69f8d3a6da1c6e077"
const REDIRECT_URI = "https://groove-music-app.vercel.app/onboarding"
const AUTH_ENDPOINT = "https://accounts.spotify.com/authorize"
const RESPONSE_TYPE = "token"

function App({ Component, pageProps }) {
    const router = useRouter();

    useEffect(() => {
        const hashParams = window.location.hash.substr(1).split("&").reduce(function (result, item) {
            const parts = item.split("=");
            result[parts[0]] = parts[1];
            return result;
        }, {});

        if (hashParams.access_token) {
            sessionStorage.setItem("spotifyToken", hashParams.access_token);
            window.history.replaceState(null, null, window.location.pathname);
        } else {
            const storedToken = sessionStorage.getItem("spotifyToken");
            if (!storedToken && router.pathname !== '/login') {
                router.push('/login');
            }
        }
    }, []);

    return (
        <>
            <Head>
                <title>GROOVE</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Component {...pageProps} />
        </>
    );
}

export default App;
